version: '3'
services:
    zookeeper:
        image: bitnami/zookeeper:${ZOOKEEPER_VERSION:-latest}
        container_name: zookeeper
        volumes:
          - ./data/zookeeper:/bitnami/zookeeper
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:${KAFKA_VERSION:-latest}
        container_name: kafka
        volumes:
          - ./data/kafka:/bitnami/kafka
        environment:
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        ports:
          - 9092:9092
        depends_on:
          - zookeeper

    kafka-ui:
        image: provectuslabs/kafka-ui:${KAFKAUI_VERSION:-latest}
        container_name: kafka-ui
        ports:
          - "8080:8080"
        environment:
          - KAFKA_CLUSTERS_0_NAME=kafka
          - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        depends_on:
          - kafka

    clickhouse:
        image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-latest}
        container_name: clickhouse
        volumes:
          - ./data/clickhouse:/var/lib/clickhouse
          - ./configs/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
          - ./configs/clickhouse/grafana.xml:/etc/clickhouse-server/users.d/grafana.xml
        ports:
          - 8123:8123
          - 9000:9000
        ulimits:
          nofile:
            soft: 262144
            hard: 262144
        depends_on:
          - kafka
    
    grafana:
        image: grafana/grafana:${GRAFANA_VERSION:-latest}
        container_name: grafana
        environment:
          - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
          - GF_AUTH_ANONYMOUS_ENABLED=true
        volumes:
          - ./configs/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
          - ./configs/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
          - ./configs/grafana/alerts.json:/etc/grafana/provisioning/dashboards/alerts.json
        ports:
          - 3000:3000
        depends_on:
          - clickhouse      

    pygenerator:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: pygenerator
        restart: always
        environment:
          - BID_SIZE=50
          - ASK_SIZE=50
          - RANDOM_START=1
          - RANDOM_DECIMAL=1
          - CREATE_REPORT_INTERVAL=0.1
          - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
          - KAFKA_TOPIC=metrics_raw
        depends_on:
          - kafka
          - clickhouse
