apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: grafana
      tlsSkipVerify: true
    secureJsonData:
      password: grafana